"use client";

import { useEffect } from 'react';

export default function PwaInit() {
  useEffect(() => {
    if (typeof window === 'undefined') return;
    if (!('serviceWorker' in navigator)) return;
    if (process.env.NODE_ENV !== 'production') return;

    // The service worker is generated by Serwist at build time.
    navigator.serviceWorker
      .register('/sw.js', { scope: '/' })
      .catch(() => {
        // Swallow registration errors. The app still works online without the SW.
      });
  }, []);

  return null;
}
